# Generated by Django 6.0.3 on 2026-03-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, verbose_name='Notas Clínicas'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, verbose_name='Prescrição'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
