# Generated by Django 6.0.3 on 2026-03-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_clinical_notes_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthplan',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='healthplan',
            name='validity_days',
            field=models.IntegerField(default=30, verbose_name='Dias de Validade'),
        ),
    ]
