# Generated by Django 6.0.3 on 2026-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_healthplan_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='professional',
        ),
        migrations.AddField(
            model_name='healthplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='percentage_medical_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Percentual Médico'),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='percentage_nutrition_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Percentual Nutricionista'),
        ),
    ]
