# Generated by Django 6.0.3 on 2026-03-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Sobrenome'),
        ),
    ]
