# Generated by Django 6.0.3 on 2026-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_appointment_body_fat_percentage_and_more'),
    ]

    operations = [

    ]
