# Generated by Django 6.0.3 on 2026-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_remove_appointment_status_and_more'),
    ]

    operations = [
    ]
