# Generated by Django 6.0.3 on 2026-03-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_fix_appointment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointments/attachments/', verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinic.appointment', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Anexo de Consulta',
                'verbose_name_plural': 'Anexos de Consulta',
            },
        ),
    ]
