# Generated by Django 6.0.3 on 2026-03-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_appointment_status_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (m)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('mora_com_quem', models.TextField(verbose_name='Mora com quem?')),
                ('tem_dia_lista_compras', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Tem dia para fazer lista de compras?')),
                ('como_e_lista_compras', models.TextField(verbose_name='Como é sua lista de compras?')),
                ('fenotipo', models.TextField(verbose_name='Fenótipo?')),
                ('o_que_incomoda', models.TextField(verbose_name='O que incomoda você hoje?')),
                ('imc_avaliacao', models.TextField(verbose_name='IMC/Avaliação')),
                ('circunferencia_abdominal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Circunferência Abdominal (cm)')),
                ('objetivo', models.TextField(verbose_name='Qual seu objetivo hoje?')),
                ('treino', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Treino?')),
                ('intestino', models.CharField(choices=[('Funciona bem', 'Funciona bem'), ('Não funciona bem', 'Não funciona bem')], max_length=20, verbose_name='Intestino?')),
                ('aversao', models.TextField(verbose_name='Aversão?')),
                ('organizacao', models.TextField(verbose_name='Como pretende se organizar?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='clinic.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
