# Generated by Django 6.0.3 on 2026-03-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='historico_peso',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Evolução de Peso'),
        ),
    ]
