# Generated by Django 6.0.3 on 2026-03-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_remove_appointment_status_anamnese_historico_peso_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='anamnese',
            name='imc_avaliacao',
            field=models.CharField(choices=[('Abaixo do peso', 'Abaixo do peso'), ('Peso normal', 'Peso normal'), ('Sobrepeso', 'Sobrepeso'), ('Obesidade Grau I', 'Obesidade Grau I'), ('Obesidade Grau II', 'Obesidade Grau II'), ('Obesidade Grau III', 'Obesidade Grau III')], max_length=20, verbose_name='IMC/Avaliação'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='intestino',
            field=models.TextField(verbose_name='Intestino?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='treino',
            field=models.TextField(verbose_name='Treino?'),
        ),
    ]
