# Generated by Django 6.0.3 on 2026-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_appointment_status_anamnese_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),

        migrations.AlterField(
            model_name='anamnese',
            name='mora_com_quem',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mora com quem?'),
        ),
    ]
