# Generated by Django 6.0.3 on 2026-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_remove_appointment_status_anamnese_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='doenca_intolerancia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doença/Intolerância?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medicamentos?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sono?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='toma_agua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Toma água?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='mora_com_quem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mora com quem?'),
        ),
    ]
