# Generated by Django 6.0.3 on 2026-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_remove_appointment_status_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='anamnese',
            name='aversao',
            field=models.CharField(max_length=100, verbose_name='Aversão?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='intestino',
            field=models.CharField(max_length=100, verbose_name='Intestino?'),
        ),
    ]
