# Generated by Django 6.0.3 on 2026-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='aversao',
            field=models.CharField(max_length=100, null=True, verbose_name='Aversão?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='cidade',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='doenca_intolerancia',
            field=models.CharField(max_length=100, null=True, verbose_name='Doença/Intolerância?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='estado',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='historico_peso',
            field=models.TextField(null=True, verbose_name='Histórico de Evolução de Peso'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='idade',
            field=models.IntegerField(null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='intestino',
            field=models.CharField(max_length=100, null=True, verbose_name='Intestino?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medicamentos',
            field=models.CharField(max_length=100, null=True, verbose_name='Medicamentos?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='organizacao',
            field=models.TextField(null=True, verbose_name='Como pretende se organizar?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='profissao',
            field=models.CharField(max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='sono',
            field=models.CharField(max_length=100, null=True, verbose_name='Sono?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='toma_agua',
            field=models.CharField(max_length=100, null=True, verbose_name='Toma água?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='treino',
            field=models.TextField(null=True, verbose_name='Treino?'),
        ),
    ]
