# Generated by Django 6.0.3 on 2026-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_remove_appointment_status_and_more'),
    ]

    operations = [
    ]
