# Generated by Django 6.0.3 on 2026-04-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='nome',
        ),
    ]
